
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ServiceReview` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ServiceReview
 * 
 */
export type ServiceReviewModel = runtime.Types.Result.DefaultSelection<Prisma.$ServiceReviewPayload>

export type AggregateServiceReview = {
  _count: ServiceReviewCountAggregateOutputType | null
  _avg: ServiceReviewAvgAggregateOutputType | null
  _sum: ServiceReviewSumAggregateOutputType | null
  _min: ServiceReviewMinAggregateOutputType | null
  _max: ServiceReviewMaxAggregateOutputType | null
}

export type ServiceReviewAvgAggregateOutputType = {
  rating: number | null
}

export type ServiceReviewSumAggregateOutputType = {
  rating: number | null
}

export type ServiceReviewMinAggregateOutputType = {
  id: string | null
  rating: number | null
  createdAt: Date | null
  updatedAt: Date | null
  bookingId: string | null
}

export type ServiceReviewMaxAggregateOutputType = {
  id: string | null
  rating: number | null
  createdAt: Date | null
  updatedAt: Date | null
  bookingId: string | null
}

export type ServiceReviewCountAggregateOutputType = {
  id: number
  rating: number
  createdAt: number
  updatedAt: number
  bookingId: number
  _all: number
}


export type ServiceReviewAvgAggregateInputType = {
  rating?: true
}

export type ServiceReviewSumAggregateInputType = {
  rating?: true
}

export type ServiceReviewMinAggregateInputType = {
  id?: true
  rating?: true
  createdAt?: true
  updatedAt?: true
  bookingId?: true
}

export type ServiceReviewMaxAggregateInputType = {
  id?: true
  rating?: true
  createdAt?: true
  updatedAt?: true
  bookingId?: true
}

export type ServiceReviewCountAggregateInputType = {
  id?: true
  rating?: true
  createdAt?: true
  updatedAt?: true
  bookingId?: true
  _all?: true
}

export type ServiceReviewAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceReview to aggregate.
   */
  where?: Prisma.ServiceReviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceReviews to fetch.
   */
  orderBy?: Prisma.ServiceReviewOrderByWithRelationInput | Prisma.ServiceReviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ServiceReviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceReviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceReviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ServiceReviews
  **/
  _count?: true | ServiceReviewCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ServiceReviewAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ServiceReviewSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ServiceReviewMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ServiceReviewMaxAggregateInputType
}

export type GetServiceReviewAggregateType<T extends ServiceReviewAggregateArgs> = {
      [P in keyof T & keyof AggregateServiceReview]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateServiceReview[P]>
    : Prisma.GetScalarType<T[P], AggregateServiceReview[P]>
}




export type ServiceReviewGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceReviewWhereInput
  orderBy?: Prisma.ServiceReviewOrderByWithAggregationInput | Prisma.ServiceReviewOrderByWithAggregationInput[]
  by: Prisma.ServiceReviewScalarFieldEnum[] | Prisma.ServiceReviewScalarFieldEnum
  having?: Prisma.ServiceReviewScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ServiceReviewCountAggregateInputType | true
  _avg?: ServiceReviewAvgAggregateInputType
  _sum?: ServiceReviewSumAggregateInputType
  _min?: ServiceReviewMinAggregateInputType
  _max?: ServiceReviewMaxAggregateInputType
}

export type ServiceReviewGroupByOutputType = {
  id: string
  rating: number
  createdAt: Date
  updatedAt: Date
  bookingId: string
  _count: ServiceReviewCountAggregateOutputType | null
  _avg: ServiceReviewAvgAggregateOutputType | null
  _sum: ServiceReviewSumAggregateOutputType | null
  _min: ServiceReviewMinAggregateOutputType | null
  _max: ServiceReviewMaxAggregateOutputType | null
}

export type GetServiceReviewGroupByPayload<T extends ServiceReviewGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ServiceReviewGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ServiceReviewGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ServiceReviewGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ServiceReviewGroupByOutputType[P]>
      }
    >
  >



export type ServiceReviewWhereInput = {
  AND?: Prisma.ServiceReviewWhereInput | Prisma.ServiceReviewWhereInput[]
  OR?: Prisma.ServiceReviewWhereInput[]
  NOT?: Prisma.ServiceReviewWhereInput | Prisma.ServiceReviewWhereInput[]
  id?: Prisma.StringFilter<"ServiceReview"> | string
  rating?: Prisma.IntFilter<"ServiceReview"> | number
  createdAt?: Prisma.DateTimeFilter<"ServiceReview"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ServiceReview"> | Date | string
  bookingId?: Prisma.StringFilter<"ServiceReview"> | string
  booking?: Prisma.XOR<Prisma.BookingScalarRelationFilter, Prisma.BookingWhereInput>
}

export type ServiceReviewOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
  booking?: Prisma.BookingOrderByWithRelationInput
}

export type ServiceReviewWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  bookingId?: string
  AND?: Prisma.ServiceReviewWhereInput | Prisma.ServiceReviewWhereInput[]
  OR?: Prisma.ServiceReviewWhereInput[]
  NOT?: Prisma.ServiceReviewWhereInput | Prisma.ServiceReviewWhereInput[]
  rating?: Prisma.IntFilter<"ServiceReview"> | number
  createdAt?: Prisma.DateTimeFilter<"ServiceReview"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ServiceReview"> | Date | string
  booking?: Prisma.XOR<Prisma.BookingScalarRelationFilter, Prisma.BookingWhereInput>
}, "id" | "bookingId">

export type ServiceReviewOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
  _count?: Prisma.ServiceReviewCountOrderByAggregateInput
  _avg?: Prisma.ServiceReviewAvgOrderByAggregateInput
  _max?: Prisma.ServiceReviewMaxOrderByAggregateInput
  _min?: Prisma.ServiceReviewMinOrderByAggregateInput
  _sum?: Prisma.ServiceReviewSumOrderByAggregateInput
}

export type ServiceReviewScalarWhereWithAggregatesInput = {
  AND?: Prisma.ServiceReviewScalarWhereWithAggregatesInput | Prisma.ServiceReviewScalarWhereWithAggregatesInput[]
  OR?: Prisma.ServiceReviewScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ServiceReviewScalarWhereWithAggregatesInput | Prisma.ServiceReviewScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ServiceReview"> | string
  rating?: Prisma.IntWithAggregatesFilter<"ServiceReview"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ServiceReview"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ServiceReview"> | Date | string
  bookingId?: Prisma.StringWithAggregatesFilter<"ServiceReview"> | string
}

export type ServiceReviewCreateInput = {
  id?: string
  rating: number
  createdAt?: Date | string
  updatedAt?: Date | string
  booking: Prisma.BookingCreateNestedOneWithoutReviewInput
}

export type ServiceReviewUncheckedCreateInput = {
  id?: string
  rating: number
  createdAt?: Date | string
  updatedAt?: Date | string
  bookingId: string
}

export type ServiceReviewUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  booking?: Prisma.BookingUpdateOneRequiredWithoutReviewNestedInput
}

export type ServiceReviewUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  bookingId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ServiceReviewCreateManyInput = {
  id?: string
  rating: number
  createdAt?: Date | string
  updatedAt?: Date | string
  bookingId: string
}

export type ServiceReviewUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceReviewUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  bookingId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ServiceReviewNullableScalarRelationFilter = {
  is?: Prisma.ServiceReviewWhereInput | null
  isNot?: Prisma.ServiceReviewWhereInput | null
}

export type ServiceReviewCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
}

export type ServiceReviewAvgOrderByAggregateInput = {
  rating?: Prisma.SortOrder
}

export type ServiceReviewMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
}

export type ServiceReviewMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  bookingId?: Prisma.SortOrder
}

export type ServiceReviewSumOrderByAggregateInput = {
  rating?: Prisma.SortOrder
}

export type ServiceReviewCreateNestedOneWithoutBookingInput = {
  create?: Prisma.XOR<Prisma.ServiceReviewCreateWithoutBookingInput, Prisma.ServiceReviewUncheckedCreateWithoutBookingInput>
  connectOrCreate?: Prisma.ServiceReviewCreateOrConnectWithoutBookingInput
  connect?: Prisma.ServiceReviewWhereUniqueInput
}

export type ServiceReviewUncheckedCreateNestedOneWithoutBookingInput = {
  create?: Prisma.XOR<Prisma.ServiceReviewCreateWithoutBookingInput, Prisma.ServiceReviewUncheckedCreateWithoutBookingInput>
  connectOrCreate?: Prisma.ServiceReviewCreateOrConnectWithoutBookingInput
  connect?: Prisma.ServiceReviewWhereUniqueInput
}

export type ServiceReviewUpdateOneWithoutBookingNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceReviewCreateWithoutBookingInput, Prisma.ServiceReviewUncheckedCreateWithoutBookingInput>
  connectOrCreate?: Prisma.ServiceReviewCreateOrConnectWithoutBookingInput
  upsert?: Prisma.ServiceReviewUpsertWithoutBookingInput
  disconnect?: Prisma.ServiceReviewWhereInput | boolean
  delete?: Prisma.ServiceReviewWhereInput | boolean
  connect?: Prisma.ServiceReviewWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ServiceReviewUpdateToOneWithWhereWithoutBookingInput, Prisma.ServiceReviewUpdateWithoutBookingInput>, Prisma.ServiceReviewUncheckedUpdateWithoutBookingInput>
}

export type ServiceReviewUncheckedUpdateOneWithoutBookingNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceReviewCreateWithoutBookingInput, Prisma.ServiceReviewUncheckedCreateWithoutBookingInput>
  connectOrCreate?: Prisma.ServiceReviewCreateOrConnectWithoutBookingInput
  upsert?: Prisma.ServiceReviewUpsertWithoutBookingInput
  disconnect?: Prisma.ServiceReviewWhereInput | boolean
  delete?: Prisma.ServiceReviewWhereInput | boolean
  connect?: Prisma.ServiceReviewWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ServiceReviewUpdateToOneWithWhereWithoutBookingInput, Prisma.ServiceReviewUpdateWithoutBookingInput>, Prisma.ServiceReviewUncheckedUpdateWithoutBookingInput>
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ServiceReviewCreateWithoutBookingInput = {
  id?: string
  rating: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ServiceReviewUncheckedCreateWithoutBookingInput = {
  id?: string
  rating: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ServiceReviewCreateOrConnectWithoutBookingInput = {
  where: Prisma.ServiceReviewWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceReviewCreateWithoutBookingInput, Prisma.ServiceReviewUncheckedCreateWithoutBookingInput>
}

export type ServiceReviewUpsertWithoutBookingInput = {
  update: Prisma.XOR<Prisma.ServiceReviewUpdateWithoutBookingInput, Prisma.ServiceReviewUncheckedUpdateWithoutBookingInput>
  create: Prisma.XOR<Prisma.ServiceReviewCreateWithoutBookingInput, Prisma.ServiceReviewUncheckedCreateWithoutBookingInput>
  where?: Prisma.ServiceReviewWhereInput
}

export type ServiceReviewUpdateToOneWithWhereWithoutBookingInput = {
  where?: Prisma.ServiceReviewWhereInput
  data: Prisma.XOR<Prisma.ServiceReviewUpdateWithoutBookingInput, Prisma.ServiceReviewUncheckedUpdateWithoutBookingInput>
}

export type ServiceReviewUpdateWithoutBookingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceReviewUncheckedUpdateWithoutBookingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ServiceReviewSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  rating?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  bookingId?: boolean
  booking?: boolean | Prisma.BookingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceReview"]>

export type ServiceReviewSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  rating?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  bookingId?: boolean
  booking?: boolean | Prisma.BookingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceReview"]>

export type ServiceReviewSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  rating?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  bookingId?: boolean
  booking?: boolean | Prisma.BookingDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceReview"]>

export type ServiceReviewSelectScalar = {
  id?: boolean
  rating?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  bookingId?: boolean
}

export type ServiceReviewOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "rating" | "createdAt" | "updatedAt" | "bookingId", ExtArgs["result"]["serviceReview"]>
export type ServiceReviewInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  booking?: boolean | Prisma.BookingDefaultArgs<ExtArgs>
}
export type ServiceReviewIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  booking?: boolean | Prisma.BookingDefaultArgs<ExtArgs>
}
export type ServiceReviewIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  booking?: boolean | Prisma.BookingDefaultArgs<ExtArgs>
}

export type $ServiceReviewPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ServiceReview"
  objects: {
    booking: Prisma.$BookingPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    rating: number
    createdAt: Date
    updatedAt: Date
    bookingId: string
  }, ExtArgs["result"]["serviceReview"]>
  composites: {}
}

export type ServiceReviewGetPayload<S extends boolean | null | undefined | ServiceReviewDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ServiceReviewPayload, S>

export type ServiceReviewCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ServiceReviewFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ServiceReviewCountAggregateInputType | true
  }

export interface ServiceReviewDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ServiceReview'], meta: { name: 'ServiceReview' } }
  /**
   * Find zero or one ServiceReview that matches the filter.
   * @param {ServiceReviewFindUniqueArgs} args - Arguments to find a ServiceReview
   * @example
   * // Get one ServiceReview
   * const serviceReview = await prisma.serviceReview.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ServiceReviewFindUniqueArgs>(args: Prisma.SelectSubset<T, ServiceReviewFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ServiceReviewClient<runtime.Types.Result.GetResult<Prisma.$ServiceReviewPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ServiceReview that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ServiceReviewFindUniqueOrThrowArgs} args - Arguments to find a ServiceReview
   * @example
   * // Get one ServiceReview
   * const serviceReview = await prisma.serviceReview.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ServiceReviewFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ServiceReviewFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceReviewClient<runtime.Types.Result.GetResult<Prisma.$ServiceReviewPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceReview that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceReviewFindFirstArgs} args - Arguments to find a ServiceReview
   * @example
   * // Get one ServiceReview
   * const serviceReview = await prisma.serviceReview.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ServiceReviewFindFirstArgs>(args?: Prisma.SelectSubset<T, ServiceReviewFindFirstArgs<ExtArgs>>): Prisma.Prisma__ServiceReviewClient<runtime.Types.Result.GetResult<Prisma.$ServiceReviewPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceReview that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceReviewFindFirstOrThrowArgs} args - Arguments to find a ServiceReview
   * @example
   * // Get one ServiceReview
   * const serviceReview = await prisma.serviceReview.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ServiceReviewFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ServiceReviewFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceReviewClient<runtime.Types.Result.GetResult<Prisma.$ServiceReviewPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ServiceReviews that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceReviewFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ServiceReviews
   * const serviceReviews = await prisma.serviceReview.findMany()
   * 
   * // Get first 10 ServiceReviews
   * const serviceReviews = await prisma.serviceReview.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const serviceReviewWithIdOnly = await prisma.serviceReview.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ServiceReviewFindManyArgs>(args?: Prisma.SelectSubset<T, ServiceReviewFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceReviewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ServiceReview.
   * @param {ServiceReviewCreateArgs} args - Arguments to create a ServiceReview.
   * @example
   * // Create one ServiceReview
   * const ServiceReview = await prisma.serviceReview.create({
   *   data: {
   *     // ... data to create a ServiceReview
   *   }
   * })
   * 
   */
  create<T extends ServiceReviewCreateArgs>(args: Prisma.SelectSubset<T, ServiceReviewCreateArgs<ExtArgs>>): Prisma.Prisma__ServiceReviewClient<runtime.Types.Result.GetResult<Prisma.$ServiceReviewPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ServiceReviews.
   * @param {ServiceReviewCreateManyArgs} args - Arguments to create many ServiceReviews.
   * @example
   * // Create many ServiceReviews
   * const serviceReview = await prisma.serviceReview.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ServiceReviewCreateManyArgs>(args?: Prisma.SelectSubset<T, ServiceReviewCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ServiceReviews and returns the data saved in the database.
   * @param {ServiceReviewCreateManyAndReturnArgs} args - Arguments to create many ServiceReviews.
   * @example
   * // Create many ServiceReviews
   * const serviceReview = await prisma.serviceReview.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ServiceReviews and only return the `id`
   * const serviceReviewWithIdOnly = await prisma.serviceReview.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ServiceReviewCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ServiceReviewCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceReviewPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ServiceReview.
   * @param {ServiceReviewDeleteArgs} args - Arguments to delete one ServiceReview.
   * @example
   * // Delete one ServiceReview
   * const ServiceReview = await prisma.serviceReview.delete({
   *   where: {
   *     // ... filter to delete one ServiceReview
   *   }
   * })
   * 
   */
  delete<T extends ServiceReviewDeleteArgs>(args: Prisma.SelectSubset<T, ServiceReviewDeleteArgs<ExtArgs>>): Prisma.Prisma__ServiceReviewClient<runtime.Types.Result.GetResult<Prisma.$ServiceReviewPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ServiceReview.
   * @param {ServiceReviewUpdateArgs} args - Arguments to update one ServiceReview.
   * @example
   * // Update one ServiceReview
   * const serviceReview = await prisma.serviceReview.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ServiceReviewUpdateArgs>(args: Prisma.SelectSubset<T, ServiceReviewUpdateArgs<ExtArgs>>): Prisma.Prisma__ServiceReviewClient<runtime.Types.Result.GetResult<Prisma.$ServiceReviewPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ServiceReviews.
   * @param {ServiceReviewDeleteManyArgs} args - Arguments to filter ServiceReviews to delete.
   * @example
   * // Delete a few ServiceReviews
   * const { count } = await prisma.serviceReview.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ServiceReviewDeleteManyArgs>(args?: Prisma.SelectSubset<T, ServiceReviewDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceReviews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceReviewUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ServiceReviews
   * const serviceReview = await prisma.serviceReview.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ServiceReviewUpdateManyArgs>(args: Prisma.SelectSubset<T, ServiceReviewUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceReviews and returns the data updated in the database.
   * @param {ServiceReviewUpdateManyAndReturnArgs} args - Arguments to update many ServiceReviews.
   * @example
   * // Update many ServiceReviews
   * const serviceReview = await prisma.serviceReview.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ServiceReviews and only return the `id`
   * const serviceReviewWithIdOnly = await prisma.serviceReview.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ServiceReviewUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ServiceReviewUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceReviewPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ServiceReview.
   * @param {ServiceReviewUpsertArgs} args - Arguments to update or create a ServiceReview.
   * @example
   * // Update or create a ServiceReview
   * const serviceReview = await prisma.serviceReview.upsert({
   *   create: {
   *     // ... data to create a ServiceReview
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ServiceReview we want to update
   *   }
   * })
   */
  upsert<T extends ServiceReviewUpsertArgs>(args: Prisma.SelectSubset<T, ServiceReviewUpsertArgs<ExtArgs>>): Prisma.Prisma__ServiceReviewClient<runtime.Types.Result.GetResult<Prisma.$ServiceReviewPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ServiceReviews.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceReviewCountArgs} args - Arguments to filter ServiceReviews to count.
   * @example
   * // Count the number of ServiceReviews
   * const count = await prisma.serviceReview.count({
   *   where: {
   *     // ... the filter for the ServiceReviews we want to count
   *   }
   * })
  **/
  count<T extends ServiceReviewCountArgs>(
    args?: Prisma.Subset<T, ServiceReviewCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ServiceReviewCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ServiceReview.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceReviewAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ServiceReviewAggregateArgs>(args: Prisma.Subset<T, ServiceReviewAggregateArgs>): Prisma.PrismaPromise<GetServiceReviewAggregateType<T>>

  /**
   * Group by ServiceReview.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceReviewGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ServiceReviewGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ServiceReviewGroupByArgs['orderBy'] }
      : { orderBy?: ServiceReviewGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ServiceReviewGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetServiceReviewGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ServiceReview model
 */
readonly fields: ServiceReviewFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ServiceReview.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ServiceReviewClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  booking<T extends Prisma.BookingDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BookingDefaultArgs<ExtArgs>>): Prisma.Prisma__BookingClient<runtime.Types.Result.GetResult<Prisma.$BookingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ServiceReview model
 */
export interface ServiceReviewFieldRefs {
  readonly id: Prisma.FieldRef<"ServiceReview", 'String'>
  readonly rating: Prisma.FieldRef<"ServiceReview", 'Int'>
  readonly createdAt: Prisma.FieldRef<"ServiceReview", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ServiceReview", 'DateTime'>
  readonly bookingId: Prisma.FieldRef<"ServiceReview", 'String'>
}
    

// Custom InputTypes
/**
 * ServiceReview findUnique
 */
export type ServiceReviewFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceReview
   */
  select?: Prisma.ServiceReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceReview
   */
  omit?: Prisma.ServiceReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceReviewInclude<ExtArgs> | null
  /**
   * Filter, which ServiceReview to fetch.
   */
  where: Prisma.ServiceReviewWhereUniqueInput
}

/**
 * ServiceReview findUniqueOrThrow
 */
export type ServiceReviewFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceReview
   */
  select?: Prisma.ServiceReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceReview
   */
  omit?: Prisma.ServiceReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceReviewInclude<ExtArgs> | null
  /**
   * Filter, which ServiceReview to fetch.
   */
  where: Prisma.ServiceReviewWhereUniqueInput
}

/**
 * ServiceReview findFirst
 */
export type ServiceReviewFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceReview
   */
  select?: Prisma.ServiceReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceReview
   */
  omit?: Prisma.ServiceReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceReviewInclude<ExtArgs> | null
  /**
   * Filter, which ServiceReview to fetch.
   */
  where?: Prisma.ServiceReviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceReviews to fetch.
   */
  orderBy?: Prisma.ServiceReviewOrderByWithRelationInput | Prisma.ServiceReviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceReviews.
   */
  cursor?: Prisma.ServiceReviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceReviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceReviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceReviews.
   */
  distinct?: Prisma.ServiceReviewScalarFieldEnum | Prisma.ServiceReviewScalarFieldEnum[]
}

/**
 * ServiceReview findFirstOrThrow
 */
export type ServiceReviewFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceReview
   */
  select?: Prisma.ServiceReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceReview
   */
  omit?: Prisma.ServiceReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceReviewInclude<ExtArgs> | null
  /**
   * Filter, which ServiceReview to fetch.
   */
  where?: Prisma.ServiceReviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceReviews to fetch.
   */
  orderBy?: Prisma.ServiceReviewOrderByWithRelationInput | Prisma.ServiceReviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceReviews.
   */
  cursor?: Prisma.ServiceReviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceReviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceReviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceReviews.
   */
  distinct?: Prisma.ServiceReviewScalarFieldEnum | Prisma.ServiceReviewScalarFieldEnum[]
}

/**
 * ServiceReview findMany
 */
export type ServiceReviewFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceReview
   */
  select?: Prisma.ServiceReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceReview
   */
  omit?: Prisma.ServiceReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceReviewInclude<ExtArgs> | null
  /**
   * Filter, which ServiceReviews to fetch.
   */
  where?: Prisma.ServiceReviewWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceReviews to fetch.
   */
  orderBy?: Prisma.ServiceReviewOrderByWithRelationInput | Prisma.ServiceReviewOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ServiceReviews.
   */
  cursor?: Prisma.ServiceReviewWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceReviews from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceReviews.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceReviews.
   */
  distinct?: Prisma.ServiceReviewScalarFieldEnum | Prisma.ServiceReviewScalarFieldEnum[]
}

/**
 * ServiceReview create
 */
export type ServiceReviewCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceReview
   */
  select?: Prisma.ServiceReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceReview
   */
  omit?: Prisma.ServiceReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceReviewInclude<ExtArgs> | null
  /**
   * The data needed to create a ServiceReview.
   */
  data: Prisma.XOR<Prisma.ServiceReviewCreateInput, Prisma.ServiceReviewUncheckedCreateInput>
}

/**
 * ServiceReview createMany
 */
export type ServiceReviewCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ServiceReviews.
   */
  data: Prisma.ServiceReviewCreateManyInput | Prisma.ServiceReviewCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ServiceReview createManyAndReturn
 */
export type ServiceReviewCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceReview
   */
  select?: Prisma.ServiceReviewSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceReview
   */
  omit?: Prisma.ServiceReviewOmit<ExtArgs> | null
  /**
   * The data used to create many ServiceReviews.
   */
  data: Prisma.ServiceReviewCreateManyInput | Prisma.ServiceReviewCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceReviewIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ServiceReview update
 */
export type ServiceReviewUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceReview
   */
  select?: Prisma.ServiceReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceReview
   */
  omit?: Prisma.ServiceReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceReviewInclude<ExtArgs> | null
  /**
   * The data needed to update a ServiceReview.
   */
  data: Prisma.XOR<Prisma.ServiceReviewUpdateInput, Prisma.ServiceReviewUncheckedUpdateInput>
  /**
   * Choose, which ServiceReview to update.
   */
  where: Prisma.ServiceReviewWhereUniqueInput
}

/**
 * ServiceReview updateMany
 */
export type ServiceReviewUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ServiceReviews.
   */
  data: Prisma.XOR<Prisma.ServiceReviewUpdateManyMutationInput, Prisma.ServiceReviewUncheckedUpdateManyInput>
  /**
   * Filter which ServiceReviews to update
   */
  where?: Prisma.ServiceReviewWhereInput
  /**
   * Limit how many ServiceReviews to update.
   */
  limit?: number
}

/**
 * ServiceReview updateManyAndReturn
 */
export type ServiceReviewUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceReview
   */
  select?: Prisma.ServiceReviewSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceReview
   */
  omit?: Prisma.ServiceReviewOmit<ExtArgs> | null
  /**
   * The data used to update ServiceReviews.
   */
  data: Prisma.XOR<Prisma.ServiceReviewUpdateManyMutationInput, Prisma.ServiceReviewUncheckedUpdateManyInput>
  /**
   * Filter which ServiceReviews to update
   */
  where?: Prisma.ServiceReviewWhereInput
  /**
   * Limit how many ServiceReviews to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceReviewIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ServiceReview upsert
 */
export type ServiceReviewUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceReview
   */
  select?: Prisma.ServiceReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceReview
   */
  omit?: Prisma.ServiceReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceReviewInclude<ExtArgs> | null
  /**
   * The filter to search for the ServiceReview to update in case it exists.
   */
  where: Prisma.ServiceReviewWhereUniqueInput
  /**
   * In case the ServiceReview found by the `where` argument doesn't exist, create a new ServiceReview with this data.
   */
  create: Prisma.XOR<Prisma.ServiceReviewCreateInput, Prisma.ServiceReviewUncheckedCreateInput>
  /**
   * In case the ServiceReview was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ServiceReviewUpdateInput, Prisma.ServiceReviewUncheckedUpdateInput>
}

/**
 * ServiceReview delete
 */
export type ServiceReviewDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceReview
   */
  select?: Prisma.ServiceReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceReview
   */
  omit?: Prisma.ServiceReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceReviewInclude<ExtArgs> | null
  /**
   * Filter which ServiceReview to delete.
   */
  where: Prisma.ServiceReviewWhereUniqueInput
}

/**
 * ServiceReview deleteMany
 */
export type ServiceReviewDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceReviews to delete
   */
  where?: Prisma.ServiceReviewWhereInput
  /**
   * Limit how many ServiceReviews to delete.
   */
  limit?: number
}

/**
 * ServiceReview without action
 */
export type ServiceReviewDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceReview
   */
  select?: Prisma.ServiceReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceReview
   */
  omit?: Prisma.ServiceReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceReviewInclude<ExtArgs> | null
}
